# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geno_voice/endpoint/proto/tts_endpoint.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'geno_voice/endpoint/proto/tts_endpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,geno_voice/endpoint/proto/tts_endpoint.proto\x12\x16geno.voice.endpoint.v1\"\xc8\x01\n\rClientMessage\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\t\x12\x11\n\tinterrupt\x18\x05 \x01(\x08\x12\r\n\x05voice\x18\x06 \x01(\t\x12\r\n\x05speed\x18\x07 \x01(\x01\x12\x13\n\x0binstruction\x18\x08 \x01(\t\x12\x17\n\x0freference_audio\x18\t \x01(\x0c\x12\x16\n\x0ereference_text\x18\n \x01(\t\"\xc7\x02\n\rServerMessage\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\x12\r\n\x05\x61udio\x18\x04 \x01(\x0c\x12\x10\n\x08sequence\x18\x05 \x01(\x04\x12\x13\n\x0bpts_samples\x18\x06 \x01(\x04\x12\x14\n\x0csample_count\x18\x07 \x01(\r\x12\x13\n\x0bsample_rate\x18\x08 \x01(\r\x12\x10\n\x08\x65ncoding\x18\t \x01(\t\x12\r\n\x05\x66inal\x18\n \x01(\x08\x12\x10\n\x08priority\x18\x0b \x01(\t\x12\x13\n\x0bqueue_depth\x18\x0c \x01(\r\x12\x15\n\rtotal_samples\x18\r \x01(\x04\x12\x13\n\x0binterrupted\x18\x0e \x01(\x08\x12\x0c\n\x04\x63ode\x18\x0f \x01(\t\x12\x0f\n\x07message\x18\x10 \x01(\t\x12\x0c\n\x04json\x18\x11 \x01(\t2a\n\x03TTS\x12Z\n\x06Stream\x12%.geno.voice.endpoint.v1.ClientMessage\x1a%.geno.voice.endpoint.v1.ServerMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geno_voice.endpoint.proto.tts_endpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTMESSAGE']._serialized_start=73
  _globals['_CLIENTMESSAGE']._serialized_end=273
  _globals['_SERVERMESSAGE']._serialized_start=276
  _globals['_SERVERMESSAGE']._serialized_end=603
  _globals['_TTS']._serialized_start=605
  _globals['_TTS']._serialized_end=702
# @@protoc_insertion_point(module_scope)
